site_name: 浙江大学学生机器人协会
nav:
    - 首页: index.md
    - 活动: activity.md
    - 百科: pedia.md
theme:
  name: material
  palette:
    primary: blue
  language: zh
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate